/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LibrariesIdRouteImport } from './routes/libraries/$id'
import { Route as MediaIdRouteImport } from './routes/media/$id'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as ApiV1LibrariesRouteImport } from './routes/api/v1/libraries'
import { Route as ApiV1LibraryRouteImport } from './routes/api/v1/library'
import { Route as ApiV1ProgressRouteImport } from './routes/api/v1/progress'
import { Route as WatchMediaIdPartIdRouteImport } from './routes/watch/$mediaId/$partId'
import { Route as ApiV1MediaIdRouteImport } from './routes/api/v1/media/$id'
import { Route as ApiV1SettingsLibrariesRouteImport } from './routes/api/v1/settings/libraries'
import { Route as ApiV1SettingsOverviewRouteImport } from './routes/api/v1/settings/overview'
import { Route as ApiV1SettingsScanRouteImport } from './routes/api/v1/settings/scan'
import { Route as ApiV1StreamIdRouteImport } from './routes/api/v1/stream/$id'
import { Route as ApiV1SubtitlesIdRouteImport } from './routes/api/v1/subtitles/$id'
import { Route as ApiV1SettingsMetadataIdentifyRouteImport } from './routes/api/v1/settings/metadata/identify'
import { Route as ApiV1SettingsMetadataRefreshRouteImport } from './routes/api/v1/settings/metadata/refresh'
import { Route as ApiV1SettingsMetadataSearchRouteImport } from './routes/api/v1/settings/metadata/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIdRoute = LibrariesIdRouteImport.update({
  id: '/libraries/$id',
  path: '/libraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIdRoute = MediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LibrariesRoute = ApiV1LibrariesRouteImport.update({
  id: '/api/v1/libraries',
  path: '/api/v1/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LibraryRoute = ApiV1LibraryRouteImport.update({
  id: '/api/v1/library',
  path: '/api/v1/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProgressRoute = ApiV1ProgressRouteImport.update({
  id: '/api/v1/progress',
  path: '/api/v1/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMediaIdPartIdRoute = WatchMediaIdPartIdRouteImport.update({
  id: '/watch/$mediaId/$partId',
  path: '/watch/$mediaId/$partId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaIdRoute = ApiV1MediaIdRouteImport.update({
  id: '/api/v1/media/$id',
  path: '/api/v1/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsLibrariesRoute = ApiV1SettingsLibrariesRouteImport.update({
  id: '/api/v1/settings/libraries',
  path: '/api/v1/settings/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsOverviewRoute = ApiV1SettingsOverviewRouteImport.update({
  id: '/api/v1/settings/overview',
  path: '/api/v1/settings/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsScanRoute = ApiV1SettingsScanRouteImport.update({
  id: '/api/v1/settings/scan',
  path: '/api/v1/settings/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StreamIdRoute = ApiV1StreamIdRouteImport.update({
  id: '/api/v1/stream/$id',
  path: '/api/v1/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SubtitlesIdRoute = ApiV1SubtitlesIdRouteImport.update({
  id: '/api/v1/subtitles/$id',
  path: '/api/v1/subtitles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SettingsMetadataIdentifyRoute =
  ApiV1SettingsMetadataIdentifyRouteImport.update({
    id: '/api/v1/settings/metadata/identify',
    path: '/api/v1/settings/metadata/identify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SettingsMetadataRefreshRoute =
  ApiV1SettingsMetadataRefreshRouteImport.update({
    id: '/api/v1/settings/metadata/refresh',
    path: '/api/v1/settings/metadata/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SettingsMetadataSearchRoute =
  ApiV1SettingsMetadataSearchRouteImport.update({
    id: '/api/v1/settings/metadata/search',
    path: '/api/v1/settings/metadata/search',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/libraries/$id': typeof LibrariesIdRoute
  '/media/$id': typeof MediaIdRoute
  '/api/v1/libraries': typeof ApiV1LibrariesRoute
  '/api/v1/library': typeof ApiV1LibraryRoute
  '/api/v1/progress': typeof ApiV1ProgressRoute
  '/watch/$mediaId/$partId': typeof WatchMediaIdPartIdRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/settings/libraries': typeof ApiV1SettingsLibrariesRoute
  '/api/v1/settings/overview': typeof ApiV1SettingsOverviewRoute
  '/api/v1/settings/scan': typeof ApiV1SettingsScanRoute
  '/api/v1/stream/$id': typeof ApiV1StreamIdRoute
  '/api/v1/subtitles/$id': typeof ApiV1SubtitlesIdRoute
  '/api/v1/settings/metadata/identify': typeof ApiV1SettingsMetadataIdentifyRoute
  '/api/v1/settings/metadata/refresh': typeof ApiV1SettingsMetadataRefreshRoute
  '/api/v1/settings/metadata/search': typeof ApiV1SettingsMetadataSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/libraries/$id': typeof LibrariesIdRoute
  '/media/$id': typeof MediaIdRoute
  '/api/v1/libraries': typeof ApiV1LibrariesRoute
  '/api/v1/library': typeof ApiV1LibraryRoute
  '/api/v1/progress': typeof ApiV1ProgressRoute
  '/watch/$mediaId/$partId': typeof WatchMediaIdPartIdRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/settings/libraries': typeof ApiV1SettingsLibrariesRoute
  '/api/v1/settings/overview': typeof ApiV1SettingsOverviewRoute
  '/api/v1/settings/scan': typeof ApiV1SettingsScanRoute
  '/api/v1/stream/$id': typeof ApiV1StreamIdRoute
  '/api/v1/subtitles/$id': typeof ApiV1SubtitlesIdRoute
  '/api/v1/settings/metadata/identify': typeof ApiV1SettingsMetadataIdentifyRoute
  '/api/v1/settings/metadata/refresh': typeof ApiV1SettingsMetadataRefreshRoute
  '/api/v1/settings/metadata/search': typeof ApiV1SettingsMetadataSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/libraries/$id': typeof LibrariesIdRoute
  '/media/$id': typeof MediaIdRoute
  '/api/v1/libraries': typeof ApiV1LibrariesRoute
  '/api/v1/library': typeof ApiV1LibraryRoute
  '/api/v1/progress': typeof ApiV1ProgressRoute
  '/watch/$mediaId/$partId': typeof WatchMediaIdPartIdRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/settings/libraries': typeof ApiV1SettingsLibrariesRoute
  '/api/v1/settings/overview': typeof ApiV1SettingsOverviewRoute
  '/api/v1/settings/scan': typeof ApiV1SettingsScanRoute
  '/api/v1/stream/$id': typeof ApiV1StreamIdRoute
  '/api/v1/subtitles/$id': typeof ApiV1SubtitlesIdRoute
  '/api/v1/settings/metadata/identify': typeof ApiV1SettingsMetadataIdentifyRoute
  '/api/v1/settings/metadata/refresh': typeof ApiV1SettingsMetadataRefreshRoute
  '/api/v1/settings/metadata/search': typeof ApiV1SettingsMetadataSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/libraries/$id'
    | '/media/$id'
    | '/api/v1/libraries'
    | '/api/v1/library'
    | '/api/v1/progress'
    | '/watch/$mediaId/$partId'
    | '/api/v1/'
    | '/api/v1/media/$id'
    | '/api/v1/settings/libraries'
    | '/api/v1/settings/overview'
    | '/api/v1/settings/scan'
    | '/api/v1/stream/$id'
    | '/api/v1/subtitles/$id'
    | '/api/v1/settings/metadata/identify'
    | '/api/v1/settings/metadata/refresh'
    | '/api/v1/settings/metadata/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/libraries/$id'
    | '/media/$id'
    | '/api/v1/libraries'
    | '/api/v1/library'
    | '/api/v1/progress'
    | '/watch/$mediaId/$partId'
    | '/api/v1'
    | '/api/v1/media/$id'
    | '/api/v1/settings/libraries'
    | '/api/v1/settings/overview'
    | '/api/v1/settings/scan'
    | '/api/v1/stream/$id'
    | '/api/v1/subtitles/$id'
    | '/api/v1/settings/metadata/identify'
    | '/api/v1/settings/metadata/refresh'
    | '/api/v1/settings/metadata/search'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/libraries/$id'
    | '/media/$id'
    | '/api/v1/libraries'
    | '/api/v1/library'
    | '/api/v1/progress'
    | '/watch/$mediaId/$partId'
    | '/api/v1/'
    | '/api/v1/media/$id'
    | '/api/v1/settings/libraries'
    | '/api/v1/settings/overview'
    | '/api/v1/settings/scan'
    | '/api/v1/stream/$id'
    | '/api/v1/subtitles/$id'
    | '/api/v1/settings/metadata/identify'
    | '/api/v1/settings/metadata/refresh'
    | '/api/v1/settings/metadata/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  LibrariesIdRoute: typeof LibrariesIdRoute
  MediaIdRoute: typeof MediaIdRoute
  ApiV1LibrariesRoute: typeof ApiV1LibrariesRoute
  ApiV1LibraryRoute: typeof ApiV1LibraryRoute
  ApiV1ProgressRoute: typeof ApiV1ProgressRoute
  WatchMediaIdPartIdRoute: typeof WatchMediaIdPartIdRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiV1MediaIdRoute: typeof ApiV1MediaIdRoute
  ApiV1SettingsLibrariesRoute: typeof ApiV1SettingsLibrariesRoute
  ApiV1SettingsOverviewRoute: typeof ApiV1SettingsOverviewRoute
  ApiV1SettingsScanRoute: typeof ApiV1SettingsScanRoute
  ApiV1StreamIdRoute: typeof ApiV1StreamIdRoute
  ApiV1SubtitlesIdRoute: typeof ApiV1SubtitlesIdRoute
  ApiV1SettingsMetadataIdentifyRoute: typeof ApiV1SettingsMetadataIdentifyRoute
  ApiV1SettingsMetadataRefreshRoute: typeof ApiV1SettingsMetadataRefreshRoute
  ApiV1SettingsMetadataSearchRoute: typeof ApiV1SettingsMetadataSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$id': {
      id: '/libraries/$id'
      path: '/libraries/$id'
      fullPath: '/libraries/$id'
      preLoaderRoute: typeof LibrariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$id': {
      id: '/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof MediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/libraries': {
      id: '/api/v1/libraries'
      path: '/api/v1/libraries'
      fullPath: '/api/v1/libraries'
      preLoaderRoute: typeof ApiV1LibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/library': {
      id: '/api/v1/library'
      path: '/api/v1/library'
      fullPath: '/api/v1/library'
      preLoaderRoute: typeof ApiV1LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/progress': {
      id: '/api/v1/progress'
      path: '/api/v1/progress'
      fullPath: '/api/v1/progress'
      preLoaderRoute: typeof ApiV1ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$mediaId/$partId': {
      id: '/watch/$mediaId/$partId'
      path: '/watch/$mediaId/$partId'
      fullPath: '/watch/$mediaId/$partId'
      preLoaderRoute: typeof WatchMediaIdPartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/$id': {
      id: '/api/v1/media/$id'
      path: '/api/v1/media/$id'
      fullPath: '/api/v1/media/$id'
      preLoaderRoute: typeof ApiV1MediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/libraries': {
      id: '/api/v1/settings/libraries'
      path: '/api/v1/settings/libraries'
      fullPath: '/api/v1/settings/libraries'
      preLoaderRoute: typeof ApiV1SettingsLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/overview': {
      id: '/api/v1/settings/overview'
      path: '/api/v1/settings/overview'
      fullPath: '/api/v1/settings/overview'
      preLoaderRoute: typeof ApiV1SettingsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/scan': {
      id: '/api/v1/settings/scan'
      path: '/api/v1/settings/scan'
      fullPath: '/api/v1/settings/scan'
      preLoaderRoute: typeof ApiV1SettingsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/stream/$id': {
      id: '/api/v1/stream/$id'
      path: '/api/v1/stream/$id'
      fullPath: '/api/v1/stream/$id'
      preLoaderRoute: typeof ApiV1StreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/subtitles/$id': {
      id: '/api/v1/subtitles/$id'
      path: '/api/v1/subtitles/$id'
      fullPath: '/api/v1/subtitles/$id'
      preLoaderRoute: typeof ApiV1SubtitlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/metadata/identify': {
      id: '/api/v1/settings/metadata/identify'
      path: '/api/v1/settings/metadata/identify'
      fullPath: '/api/v1/settings/metadata/identify'
      preLoaderRoute: typeof ApiV1SettingsMetadataIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/metadata/refresh': {
      id: '/api/v1/settings/metadata/refresh'
      path: '/api/v1/settings/metadata/refresh'
      fullPath: '/api/v1/settings/metadata/refresh'
      preLoaderRoute: typeof ApiV1SettingsMetadataRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/settings/metadata/search': {
      id: '/api/v1/settings/metadata/search'
      path: '/api/v1/settings/metadata/search'
      fullPath: '/api/v1/settings/metadata/search'
      preLoaderRoute: typeof ApiV1SettingsMetadataSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  LibrariesIdRoute: LibrariesIdRoute,
  MediaIdRoute: MediaIdRoute,
  ApiV1LibrariesRoute: ApiV1LibrariesRoute,
  ApiV1LibraryRoute: ApiV1LibraryRoute,
  ApiV1ProgressRoute: ApiV1ProgressRoute,
  WatchMediaIdPartIdRoute: WatchMediaIdPartIdRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiV1MediaIdRoute: ApiV1MediaIdRoute,
  ApiV1SettingsLibrariesRoute: ApiV1SettingsLibrariesRoute,
  ApiV1SettingsOverviewRoute: ApiV1SettingsOverviewRoute,
  ApiV1SettingsScanRoute: ApiV1SettingsScanRoute,
  ApiV1StreamIdRoute: ApiV1StreamIdRoute,
  ApiV1SubtitlesIdRoute: ApiV1SubtitlesIdRoute,
  ApiV1SettingsMetadataIdentifyRoute: ApiV1SettingsMetadataIdentifyRoute,
  ApiV1SettingsMetadataRefreshRoute: ApiV1SettingsMetadataRefreshRoute,
  ApiV1SettingsMetadataSearchRoute: ApiV1SettingsMetadataSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
